
language: objective-c
os: osx
osx_image: xcode9
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace V2EX.xcworkspace -scheme V2EX | xcpretty
  - xcodebuild -workspace V2EX.xcworkspace -scheme V2EX -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' | xcpretty
  